//Checked 1




#ifndef BLOCKS_HPP
#define BLOCK_HPP



#define NO_BLOCK -1

enum Blocks
{
	FLOOR_BLOCK, FLOOR_BLOCK1, FLOOR_BLOCK2, FLOOR_BLOCK3, FLOOR_BLOCK4, OPENED_DOOR_BLOCK, DOOR_BLOCK, LEFT_STONE_BLOCK,
    UP_STONE_BLOCK, RIGHT_STONE_BLOCK, DOWN_STONE_BLOCK, CORNER_NE_BLOCK, CORNER_NW_BLOCK, CORNER_SW_BLOCK, CORNER_SE_BLOCK,
    NE_BLOCK, NW_BLOCK, SW_BLOCK, SE_BLOCK, DOOR_UP, DOOR_DOWN, DOOR_RIGHT, DOOR_LEFT
};
#define SOLID_LIMIT 7

#define VISIBLE_WALL 18


//object IDs
#define TABLET_ID 0
#define STAIRS_ID 1
#define SPIKES_ID 2
#define SPIKES_FIRED_ID 3
#define CHAINS_ACTIVE_ID 4
#define CHAINS_ID 5
#define STATUE_ID 6
#define PILLAR_ID 7
#define CHEST_ID 8
#define OPENED_CHEST 9


//walls

#define WALL_UP 0
#define WALL_RIGHT 1
#define WALL_DOWN 2
#define WALL_LEFT 3
#define WALL_NW 4
#define WALL_NE 5
#define WALL_SE 6
#define WALL_SW 7

//pathfinder types
#define PATH_WITH_DOORS 0
#define PATH_PLAYER 1




#endif